### ISSUE TITLE
Error on activating the addon 2.80 in prefferences 

### ISSUE THREAD

**Issue by vipertkd** [p2or/blender-loom#4] opened 2019-06-27 14:24 UTC
hi.

I instaled the addon on blender 2.80 buld from 26.06.2019 and when I'm trying to activate the addon it trows me some errors.

Traceback (most recent call last):
  File "C:\Program Files\Blender 2.80 beta\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\RASVAN PAVEL\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\loom.py", line 26, in <module>
    from numpy import arange, around, isclose
  File "C:\Program Files\Blender 2.80 beta\2.80\python\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Program Files\Blender 2.80 beta\2.80\python\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Program Files\Blender 2.80 beta\2.80\python\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Program Files\Blender 2.80 beta\2.80\python\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
ImportError: cannot import name 'core' from 'numpy' (C:\Program Files\Blender 2.80 beta\2.80\python\lib\site-packages\numpy\__init__.py)

**Comment by p2or** [comment] 2019-06-27 15:15
Hi @vipertkd,

tested against the latest build on _Windows_ from today and I cannot reproduce it. Make sure you download `loom.py` file for _2.8x Beta_ from here: https://github.com/p2or/blender-loom/releases The error looks like there is something is wrong with your `numpy` library so probably a bad build...? However, I can't tell really.

Closing for now. In case the error persists, just let me know.

Cheers,
Christian

**Closed by p2or** 2019-06-27 15:15 UTC
