### ISSUE TITLE
Encoding image sequence stops halfway

### ISSUE THREAD

**Issue by Allard888** [p2or/blender-loom#13] opened 2020-12-29 10:05 UTC
When I encode an image sequence...lets say 40 frames.. .LOOM sometimes stops encoding after an random amount of frames. Sometimes it at 70%, sometimes at 56%... and sometimes it finsihes correctly..

What could be the cause of this? Im running Blender 2.9 cycles

**Comment by p2or** [comment] 2021-01-03 20:29
Hi @Allard888,

thanks for your report. Unfortunately I can not reproduce it at the moment. Could you please provide a bit more information about your _operating system_, which _ffmpeg version_ you have installed and _what settings you're actually using to encode_? If possible, provide a few frames of the shot to test against. Thanks.

Cheers,
Christian

**Comment by Allard888** [comment] 2021-01-05 11:16
Hi Christian, thank you for your reply...
I think I figured out what the problem was.. At least...when I turned off multithreading on my Ryzen, the problem didnt occur anymore.. So maybe it has to do with that? 

I have a additional question too...I reset my blender preferences to default..but when I re-enabled LOOM, the 'render image sequence' window doesnt show (ctrl shift F12)... I have tried chaning the hotkey for this..but no luck
The other 2 windows work fine...

what can this be? 

thanks!

**Comment by p2or** [comment] 2021-01-05 12:37
Hi @Allard888,

thanks. Encoding dialog is just a simple UI for [ffmpeg](https://ffmpeg.org/) and it seems your version of _ffmpeg_ can't handle multi threading instructions of your Ryzen - make sure your are using the latest version of _ffmpeg_ and set it up properly in the _Loom Preferences._ Otherwise hard to guess what's wrong since ffmpeg uses multi-threading by default, see: [FFMpeg Encoding and Core Usage](https://video.stackexchange.com/a/16004).

_Re your second question:_ For now I'd suggest just 'remove' loom (using the button in the preferences) and re-install the latest version (0.7) from here: https://github.com/p2or/blender-loom/releases  

_If there is any output in the blender console_, please [open up another issue to keep it organized](https://github.com/p2or/blender-loom/issues/new) here, thanks. In general hard to help without any further information. I'll investigate anyway and let you know. Closing for now...

Cheers,
Christian

**Closed by p2or** 2021-01-05 12:37 UTC
Labels: bug, encoding, ffmpeg

**Comment by Allard888** [comment] 2021-01-06 07:34
I apologize..I wasnt talking about the encoding of the image sequence...but the rendering of the image sequence itself :) That stops at random moments sometimes

**Comment by p2or** [comment] 2021-01-06 10:05
Hi @Allard888,

no problem. Maybe you are running out of resources or it's just a bug in Blender, not sure. _Loom_ just calls blender's rendering operator per frame so please make sure this does not happen when you are rendering the sequence without loom. The only thing I can suggest is to monitor your resources using the *Task Manager (win)*, *htop (*nix)* or the *Activity Monitor (osx)*, save to OpenEXR, enable *Save Buffers* and execute the rendering via command line to see potential errors. Otherwise I can't help much since I'm running out of ideas based on this pretty vague description of your issue. 

If you can verify that there is a bug caused by loom, please [open up a new issue](https://github.com/p2or/blender-loom/issues/new), thanks.

Cheers,
Christian

**Comment by Allard888** [comment] 2021-02-12 09:39
Thank you for your reply... 
I will try your suggestions and get back to you. 
Do you mean 'safe buffer' in the performance tab? And do you mean OpenEXR or Multilayer Open EXR? And why should I use this in stead of TIFF? 

And I know It would be easier to send you the file..but the problem is that its a 4GB file, and I signed a NDA for my client so i can't really show it to anybody.. :( So please bear with me ..

**Comment by p2or** [comment] 2021-02-12 10:50
Hi @Allard888,

yeah, exactly _Render Properties > Performance > Final Render > Save Buffers_. Have a look into https://www.openexr.com/ for further informations about the file format itself and why this becomes relevent you can read up [here](https://blender.stackexchange.com/a/16261). In case you enabled additional passes, render to *Multilayer*, otherwise just set the format to *OpenEXR*. 

As suspected, a 4gig blend is quite heavy for your hardware so I still guess you are running out of resources (gpu wise). That you are running into issues, when pushing all the data (4gig) onto your graphics card and trying to do some calculations based on that workload at the same time, is to be expected. In worst case you need to render using your cpu only. 

To even save more memory, I'd suggest:

- Setup your blend (safe buffers, exr, etc.),
- Close everthing, 
- Open up a new default blend file so blender does not need to load your heavy scene, 
- Go to *Render > Loom > Batch Render and Encode* to open up [Loom's Batch Dialog](https://github.com/p2or/blender-loom#loom-batch-dialog-ctrlshiftaltf12), 
- Add your file using the <kbd>+</kbd> button, 
- Set your ranges and hit <kbd>OK</kbd> (which basically does the same as rendering using the [command line](https://docs.blender.org/manual/en/latest/advanced/command_line/arguments.html))

Cheers,
Christian
