### ISSUE TITLE
Rendering Image Sequence with 'Maximized Area' display replaces current interface

### ISSUE THREAD

**Issue by ilcane87** [p2or/blender-loom#78] opened 2024-01-26 17:23 UTC
Hello, I assume this isn't intended behavior, but when I render a couple frames with Render Image Sequence with 'Maximized Area' option selected, instead of just overlaying the rendering area over the current interface, it also overwrites the interface itself with another maximized area, so the original interface is lost.
This behavior is unaffected by the 'Lock Interface' setting.

![issue](https://github.com/p2or/blender-loom/assets/34897042/b0f261f2-7171-4679-85d8-a8bbab6270f5)

What happens when normally rendering with Maximized Area is that after the rendering is done, you can close the overlayed area and go back to the original interface.

Running version 0.9.1 of the addon on Blender 3.5.0 (Windows 10).

**Comment by p2or** [comment] 2024-01-27 09:29
Hi @ilcane87,

thank you for your _detailed report_, I really appreciate that. I can confirm this issue and working on it. In the worst case, we have to remove the 'Maximized Area' option or recreate the entire workspace because Blender seems to lose the reference to the previously used workspace when rendering more than one frame. Is Blenders 'Maximized Area' feature something you use on a daily basis?

Cheers,
Christian

**Comment by p2or** [comment] 2024-01-28 18:32
Hi @ilcane87,

thanks for your feedback. 

> I think that's the default behavior? That or I somehow got used to it when I started with Blender, so I've been sticking with it ever since, but honestly it's just habit, I could live without it if I had to.

The default is ['New Window'](https://docs.blender.org/api/current/bpy.types.PreferencesView.html#bpy.types.PreferencesView.render_display_type), I think I would have noticed this issue sooner otherwise. 

> The only real inconvenience for me right now is that I risk forgetting about the issue and losing my interface whenever I render with the addon, so your 'worst case' would already solve this.

I keep getting crashes when I try to load or even store the previous workspace while rendering, so yeah, I don't see a better option at the moment than to remove the item from the list:

<img width="475" alt="Screenshot 2024-01-28 at 19 10 21" src="https://github.com/p2or/blender-loom/assets/512368/5896d5b1-ab37-4e46-bcaa-e5a82241ccba">

I hope you can live with it for now. If I see a good way to support "maximized area" in the future, I will look into it immediately and let you know. 

If you have the time, please clone or download _Loom_ from the master branch and report back.

Cheers,
Christian

**Comment by p2or** [comment] 2024-01-28 21:13
Hi @ilcane87, 

great, thank you for testing the patch. Closing for now, can be reopened at any time. 

Cheers, 
Christian

**Closed by p2or** 2024-01-28 21:13 UTC
Labels: bug
