### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 3: invalid start byte

### ISSUE THREAD

**Issue by vtsgarbee** [p2or/blender-loom#84] opened 2024-05-07 09:26 UTC
Hi, in several of my scenes I get this error:

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\[USERNAME]\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\loom.py", line 3963, in modal
    if not self.render_silent:
                ^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\loom.py", line 3784, in frame_repath
    file_name = replace_globals(file_name)
                                          ^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 3: invalid start byte

```

apparently it never happens on the first render, and goes away restarting blender, only to reappear on the second run.
Sometimes Blender is able to recover, sometimes crashes.

Filepath is nothing special, I usually work on a local E:/Projects/[PROJECT] folder.

Happens on win11, Blender 4.0+ loom v0.9.0 +

thanks
Federico

**Comment by vtsgarbee** [comment] 2024-05-07 10:24
ciao @p2or , thanks for your swift reply,

this is really annoying -
it's all work stuff, so i started to clean up the scene, removing the data, saving the file elsewhere, changing the outputs, etc.
I've done this two times, and both times the scene stopped having issues!

i'll try to take it more methodically and see if I can identify the cleanup steps that makes the scene work again.
This issue has happened to me multiple work files, so this must be something i do (or i have to do).

Anything else I might provide you with to help you investigate in the meantime?

ty

**Comment by p2or** [comment] 2024-05-07 10:50
Hi @vtsgarbee,

my first guess is that there is something wrong with the filepath, meaning a special character or something which has crept in and isn't readable for whatever reason. 

If this is an option for you, I would suggest to delete the geometry and all images, save the file and hand it over - makes it way easier to find the issue (can be anything in this case really).

> Anything else I might provide you with to help you investigate in the meantime?

Yeah, you could try to replace the forward slash within the output path `E:/` by either a backslash `E:\` or double-slash `E:\\` and report back.

Thanks,
Christian

**Comment by p2or** [comment] 2024-05-07 15:36
Hi @vtsgarbee,

just tested *Loom* in win10 and Blender 4.1 against the strangest file paths ever plus a similar one to yours and unfortunately I'm not able to reproduce your issue. Are there any errors from other add-ons beforehand? Did you download _Loom_ from the releases page? 

Cheers,
Christian

**Comment by p2or** [comment] 2024-05-09 17:18
Hi @vtsgarbee,

no problem, thanks for your feedback. I commented:

> i noticed that in all the problematic scenes the Blender output presents multiple version numbers, something like this:
E:\CurrentProjects[PROJECT]\render\01.BLENDER\set_05_0003_0003_0001.png

Pretty sure that this is the result of a faulty execution - looks like the frame number is appended but not reset at the end of the rendering (2 times) to me. However, I can't be sure where this is coming from... a non readable character in the path as mentioned, a faulty driver, another add-on etc. 

> now, i'm getting a bit lost - is automatic 1up on versions part of the loom tool? or might be native in blender? or even something else?

Not part of *Loom* and I'm sure this has nothing to do with the version feature since you don't use a `v` in your file path.

> the most important thing is that if i reset the output path to something reasonable, removing all the weird versioning, the problem seems to go away.

Great! I'm glad it worked out. Just in case you don't know: you can use a relative path like `//render/yourfilename_####.exr` instead of `E:/projects/render/yourfilename_####.exr` which improves readability IMHO and saves some time to set it up.

> it took me some time to notice this since I use output nodes in Compositors to save passes to different locations, and the Blender default output only to save a fallback debug beauty.

I would really like to help so if you find anything that causes this for you, please let me know and I will fix it immediately. Closing for now, can be reopened at any time.

Cheers,
Christian

**Closed by p2or** 2024-05-09 17:18 UTC
