### ISSUE TITLE
Rendering via command line randomly stops

### ISSUE THREAD

**Issue by Allard888** [p2or/blender-loom#15] opened 2021-02-12 08:35 UTC
Hi, I have a pretty long sequence that I wanted to render out with Loom. Its about 1100 frames, spread over different frame ranges (200-300, 415-550, etcetc)

I wanted Loom to render this out during the night, but when I got back it only did 17 frames and nothing more. I have tried this a couple of times...and this keeps happening . Somethimes after 50 frames, sometimes after 230 frames. It just stops. 

Just to be clear..im talking about the rendering of the images, not encoding the sequence with FFMpeg. 

Im on windows 10 64 bit, blender 2.91 and Im rendering with cycles. Also im on a AMD Threadripper system with 64 RAM.. The rendering is done with CPU+GPY (GTX 1080Ti). Please let me know if you need more info

Please advise. 

oh and a quick additional question: does blender need te be running in order to use the command line rendering? Or can I just start the command line render..and then quit Blender?

**Comment by p2or** [comment] 2021-02-12 09:12
Hi @Allard888,

thanks for your report. Does this also happen when you are rendering the sequence without the add-on? Have you tried my suggestions from: https://github.com/p2or/blender-loom/issues/13#issuecomment-755206938 already? Otherwise, can you please share the blend file so I can try to figure out? Again, hard to guess...

Cheers,
Christian

**Comment by p2or** [comment] 2021-02-12 10:53
Duplicate of #13

**Closed by p2or** 2021-02-12 10:53 UTC
