### ISSUE TITLE
Render Selected Markers: Name the output with the name of the marker

### ISSUE THREAD

**Issue by Tilix4** [p2or/blender-loom#9] opened 2020-05-26 15:29 UTC
I would be nice to be able to know from which marker is related the image by exporting the Marker name in the output name, before the image number for example.

`blendname_markername_####.png`

**Comment by p2or** [comment] 2020-05-26 19:43
Hi @Tilix4,

thanks for your proposal. However, could you please provide a bit more context and elaborate in which real world scenario this would be useful? Furthermore, do you have any ideas how we can make that accessible to the user? Any UI proposal would be nice before starting to implement something.

Cheers,
Christian

**Comment by Tilix4** [comment] 2020-05-28 07:16
Hi @p2or,

I'm currently using your add-on to storyboard a movie. I use the markers to change active camera in the timeline and I put markers to each important pose of the characters between every camera change.

<img width="757" alt="Capture d’écran 2020-05-28 à 09 15 29" src="https://user-images.githubusercontent.com/22875539/83110764-dfadd600-a0c3-11ea-8359-41e6c6c28094.png">

IMO, it could work this way:
`blendname-[activecamera-]markername-####.png`
- `blendname` is the name I put in the output field.
- `activecamera` is the name of the current active camera. (only if a marker is set to change the active camera)
- `markername` is the name of the marker currently rendered.

It would be activated by default if the marker has been renamed (blender creates markers with the frame number) and could be disabled in the add-on preferences in blender settings.

**Comment by suzannegomont** [comment] 2020-05-28 10:57
Hello there ! 

I agree with the suggestion of @Tilix4 . However, the nomenclature wouldn't work insofar as certain markers can have the same name and the same active camera. Example: a shot / countershot where we will come back to the same camera several times.

Maybe just add a number in the nomenclature if appropriate? So if the user has in his timeline the same main camera which repeats he would have something like `myrender-####[-activecamera]_##-markername_##.png`

Ideally, the user should be able to customize the output name, perhaps some won't need the active camera in this name, but only markers' names?

**Comment by p2or** [comment] 2020-05-28 11:09
Hi @Tilix4, Hi @suzannegomont, 

Thinking ahead, I'd prefer a Houdini-like list of global variables, which can be edited by the user in order to make this feature to other areas (like lookdev or layout) useful too.

| Variable       | Resolves to  |  Property
| ------------- |-------------| ---------------|
| $BLEND      | current_file_name        |  Data.filepath |
| $CAMERA   | current_camera_name |  Camera.name |
| $MARKER   | current_marker_name  |  Camera.marker |
| $SCENE      | current_scene |  Scene.name |
| $VIEWLAYER  | current_view_layer |  ViewLayer.name |
| ...   | |

However, a lot of work and the remaining issue is that if the user fills up the *output field* using these variables and going to render the *usual way*, all the file paths evaluating into a real mess on disc... and I have no idea how to deal with that at the moment. Off the top of my head a *preview of the evaluated path* in the output area as well as a *warning* or something is required to ensure the proper usage.

What do you think? 

Cheers,
Christian

**Comment by Tilix4** [comment] 2020-05-28 11:23
Maybe we could add a field in the add-on preferences `Custom naming pattern` where we would support these variables. And a checkbox in the render operator `Use custom naming pattern`, if checked, it would preview the path. This way, we don't mess with the output in the main blender output.
The custom path would be added to the last folder of the output field.

Ex:
- output field: `/path/to/my/file.ext`
- custom naming pattern: `$SCENE/$BLEND_$CAMERA-$MARKER_####`

->` /path/to/my/$SCENE/$BLEND_$CAMERA-$MARKER_####`

**Comment by p2or** [comment] 2020-05-28 12:08
Hi @Tilix4 ,

> Maybe we could add a field in the add-on preferences `Custom naming pattern` where we would support these variables.

Yeah, that's a good idea we can test.

> And a checkbox in the render operator Use custom naming pattern, if checked, it would preview the path.

Then there should be a preview of the path somewhere clearly visible before rendering.

> /path/to/my/$SCENE/$BLEND_$CAMERA-$MARKER_####

The base folder should be set in the usual *output path*, otherwise you always have to go into the *User Preferences* to change it.

> Also, we shouldn't think about all the variables, only some we will need for sure, until Blender implements its own variables.

I don't think Blender comes with something like *global variables* anytime soon, too much work I guess. 

Cheers,
Christian

**Comment by Tilix4** [comment] 2020-05-28 12:11
Hi @p2or,

I totally agree to everything you've said.

About global variables, I'm surprised nobody didn't make any add-on about it...

**Comment by p2or** [comment] 2020-05-29 14:31
Hi @Tilix4, Hi @suzannegomont,

had some time to roughly implement all the ideas from yesterday. There is a new *globals* section in the *Preferences* of the add-on where you can add a variable (starting with a dollar sign `$`) and a python expression to evaluate properties of the scene in order to add those to the file path: 

![globals-01](https://user-images.githubusercontent.com/512368/83266189-ca6ba100-a1c2-11ea-8e6b-0eaf985b3297.png)

You can do all sorts of crazy things with this and I hope this makes it useful for all of us. A few different expressions are going to be added to the list when the enabling the add-on to have something to start with. If you want to add a new expression, hit the <kbd>+</kbd>sign, enter `$YOURCOOLNAME` and assign a python expression like `bpy.context.scene.name`, which you can test before assigning by using the tester below.  We can add more defaults, just let me know.

When using these *globals* for the *output path*, a preview of the *file path* appears on the bottom of the output panel to ensure proper usage. If there is something wrong the icon turns into a `WARNING`:

![globals-out-panel](https://user-images.githubusercontent.com/512368/83267859-1b7c9480-a1c5-11ea-8c17-de3cbaffb647.png)

When using `/tmp/$BLEND_$CAMERA_$VIEWLAYER__$MARKER__###`  on the *output field* it evaluates to `/tmp/Storyboard_01_Camera_ViewLayer__F_01_001.exr` (blend file called `storybard-01.blend`, marker on frame `1` is called `F_01` ).

*Note:* For now, the actual replacement is limited to the file name itself, meaning you can not create a new folder. I created a new "globals" branch, you can download the preview from: https://github.com/p2or/blender-loom/tree/globals


Does that work for you? If you have any further ideas how to improve it, please let me know.

Cheers,
Christian

**Comment by suzannegomont** [comment] 2020-05-30 11:33
Hi @p2or , I used it this morning it works very well on my side! Thank you so much !

**Comment by p2or** [comment] 2020-06-05 12:01
Hi @Tilix4, Hi @suzannegomont 

FYI: I added 3 new operators in order to make our lives better when it comes to working with markers in general. You can now add markers (and bind them automatically) based on all selected cameras in the 3d viewport, you can also unbind and rename selected markers (using our new *globals* of course).

![marker_menu](https://user-images.githubusercontent.com/512368/83873901-ea581300-a734-11ea-9718-9d8c8cc26fff.png)

Cheers,
Christian

**Comment by p2or** [comment] 2020-06-17 11:11
@Tilix4 Any feedback before I'm going to merge branches?

**Comment by Tilix4** [comment] 2020-06-17 11:51
@p2or I'm sorry I had a very busy times these days. I'm planning to test this very soon but I cannot tell exactly when.  
If you don't want to wait I'll test it either way later and give you some feedback.

Without testing it at all, I thought maybe it would be great in future to split the variables system from the loom features. As a new project.

**Comment by Tilix4** [comment] 2020-07-12 10:15
Hi Christian,

Thank you very much for your work and sorry for the delay.

This is very nice!

My feedback and improvements I would recommend:

### Preferences
- Changing the icons of adding and removing you've set (ZOOM_IN, ZOOM_OUT) by: ADD, REMOVE. It'll be more obvious and consistent with the Blender UI.
- As we'll always use a global with '$' before (as I understood), I suggest to not have to type this symbol when we name the globals. This way, you don't have to test it to enable it or not in the UI and this is easier for a user to add one. Perhaps add a message that says: "To use a global in the output field, you must add a '$' before.". Or Maybe add a '$' grey label (`layout.enabled=False`) before, I don't know if it's possible with a template list. This way it could look like: `o | *$* | NAME | bpy.data.content...`
- The expression tester is a very nice feature! Maybe it'd be nice to add an "Add" button that would ask for a name and directly add the current expression to the list.

### Operators
- Markers from Cameras: This is very useful!
  - About the `Insert makers at the Playhead position`, maybe the 'NLA_PUSHDOWN' icon is more explicit.
  - Also, the created panel is very large and sets a lot of empty space.
- Unbind selected markers: This is useful. And maybe the opposite would be also useful: Bind selected markers. If a marker has a Camera's name, bind it. These two operators could be put in a same column on the same row.
- Batch Rename Marker: very very useful!
  - The icon might be 'FONT_DATA' but the one you've set works.
  - Maybe put 'Marker' to plural.
  - Bug: It seems to rename only binded markers. I may want to have intermediate markers between two camera changes that keeps the same naming. Maybe this could be an option enabled by default.
  - Bug: If there is an unbinded marker between two binded ones, the third marker will have its '###' number increased by two instead of one and the unbinded marker won't be renamed.

### Misc
As I've said previously, the globals you've created is maybe out of your current addon's scope. It could become a standalone addon (I've never seen one that already does that, perhaps I'm outdated).

**Comment by p2or** [comment] 2020-07-12 14:51
Hi @Tilix4,

cool! Thanks for taking the time. I agree with all the UI suggestions, good improvements, committed. I'd suggest submit a pull request next time directly, might be nice being a contributor anyway.

Regarding to **globals**: For multiple technical reasons I see no way to implement that as separate/standalone add-on at the moment - the base needs to be implemented in C. Also I think forcing the user to type the dollar sign might be good to train their memories and get how to insert the globals later on. However, you're right we can make it a label... Suggest submit a pull request.

I can't reproduce the mentioned **bug** - unbound marker number 1 as well as 3 and the names are fine:  

![bl](https://user-images.githubusercontent.com/512368/87249265-66452980-c45e-11ea-8a80-03780437a7fd.png)

Thanks again,
Christian

**Comment by Tilix4** [comment] 2020-07-12 17:20
Hi!

Thank you very much, I'll test it.
I hope I'll have time to work on a request but I don't see when...

**Comment by p2or** [comment] 2020-07-12 19:59
Hi @Tilix4,

> About a standalone addon, I'm just talking about making a "Blender Global Variables" addon which would only have the features you've added.

Yeah, I know but... I don't think it's possible to make it work at the moment, eg.: rendering as animation (<kbd>Ctrl</kbd><kbd>F12</kbd>) doesn't check/update the output path each frame so we have no control over the path per frame (one reason for loom essentially, if you are interested: https://developer.blender.org/T47530)

Cheers,
Christian

**Comment by Tilix4** [comment] 2020-07-12 21:58
Ahh I understand the main loom's goal now. This is an interesting issue and I believe your approach is the correct one. What we attend to do is kind of specific and what you're doing with loom is mostly a render farm concept. Then it makes sense and it is pretty clean actually.

**Closed** 2020-08-12 10:32 UTC
Labels: enhancement
